config/routes.rb
Rails.application.routes.draw do

  resources :pages
  devise_for :chefs
  resources :recipes do
    resources :comments, only: [:create]
  end
  root 'pages#home'
  resources :ingredients, except: [:destroy]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :recipes, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true, length: {minimum: 4, maximum: 140}
  belongs_to :chef
  belongs_to :recipe
  validates :recipe_id, presence:true
  validates :recipe_id, presence: true
  default_scope -> {order(updated_at: :desc)}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500}
  validates :chef_id, presence: true
  default_scope -> {order(updated_at: :desc)}
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:chefname])
  devise_parameter_sanitizer.permit(:account_update, keys: [:chefname])
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :chef_signed_in?
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.build(comment_params)
    @comment.chef = current_chef

    if @comment.save
      ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
      
    else
      flash[:danger] = "Comment was not created!"
      redirect_to :back
    end

  end

  private
    def comment_params
      params.require(:comment).permit(:description)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update]
  before_action :required_admin, except: [:show, :index]

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredients_params)
    if @ingredient.save
      flash[:success] = "Ingredient was created successfully"
      redirect_to @ingredient
    else
      render :new
    end
  end

  def show
    @ingredient_recipe = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  def edit
    #code
  end

  def update
    if @ingredient.update(ingredients_params)
      flash[:success] = "Ingredient name was update successfully"
      redirect_to @ingredient
    else
      render :edit
    end
  end

  private

  def set_ingredient
      @ingredient = Ingredient.find(params[:id])
  end

  def ingredients_params
      params.require(:ingredient).permit(:name)
  end

  def required_admin
    if !chef_signed_in? || (chef_signed_in? && !current_chef.admin?)
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :chef_params, only: [:show, :destroy]
  before_action :authenticate_same_chef, only: [:edit, :update, :destro]
  before_action :required_admin, only: [:destroy]

  def home
    redirect_to recipes_path if chef_signed_in?
  end
  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def show
    @chef = Chef.find(params[:id])
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
  end
  def edit
    #code
  end

  def destroy
    if !@chef.admin?
      @chef.destroy
      flash[:danger]= "Chef and all associated recipes have been deleted!"
      redirect_to pages_path()
    end
  end

  private
    def chef_params
      @chef = Chef.find(params[:id])
    end

    def authenticate_same_chef
      if current_chef != @chef and !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own account"
        redirect_to pages_path
      end
    end

    def required_admin
      if chef_signed_in? && !current_chef.admin?
        flash[:danger] = "Only admin users can perform that action"
        redirect_to root_path
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_chef!, except: [:index, :show]
  before_action :authenticate_same_chef, only: [:edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end

  # GET /recipes/new
  def new
    @recipe = current_chef.recipes.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_chef.recipes.build(recipe_params)


    if @recipe.save
      flash[:success] = "Recipe was created successfuly!"
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update

      if @recipe.update(recipe_params)
        flash[:success] = "Recipe was updated successfuly!"
        redirect_to @recipe
      else
        render :edit
      end

  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :chef_id, ingredient_ids: [])
    end

    def authenticate_same_chef
      if chef_signed_in? && (current_chef != @recipe.chef && !current_chef.admin?)
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.chefname, class: "img-circle")
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-2">
    <section class="chef_info center">
      <%= gravatar_for(comment.chef, size: 60) %>
    </section>
  </div>
  <div class="col-md-8 well">
    <p><%= comment.description %></p>
    <p>
      <span class="quiet"><small>Created:
                          <%= time_ago_in_words(comment.created_at) %> ago by
                          <%= comment.chef.chefname %></small></span>
    </p>
  </div>
</div>

app/views/comments/_comments.html.erb
<div align="center">
  <%= will_paginate comments %>
</div>
<% comments.each do |comment| %>
  <%= render(partial: 'comments/comment', object: comment) %>
<% end %>
<div align="center">
  <%= will_paginate comments %>
</div>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-md-2">
      <%= f.label :name %>
    </div>
    <div class="col-md-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter your ingredient Name", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-10 col-md-offset-2">
        <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient" , class: "btn btn-primary btn-lg btn-xlarge") %>
    </div>
  </div>

  <div class="col-md-4 col-md-offset-4 colormatch">
    [ <%= link_to "Cancel request and return to ingredients listing", ingredients_path %> ]
  </div>

<% end %>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient) %> &nbsp; </span>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "Edit ingredient name" %>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "Available Ingredients" %>

<div align="center">
  <%= will_paginate @ingredients %>
  <% @ingredients.each do |ingredient| %>
    <ul class="linting">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="chef-title"><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
          <li><small><%= pluralize(ingredient.recipes.count, "recipe") if ingredient.recipes %></small></li>
          <% if chef_signed_in? && current_chef.admin? %>
              <li><%= link_to "Edit this ingredient", edit_ingredient_path(ingredient) %></li>
          <% end %>

        </div>
      </div>
    </ul>
  <% end %>

  <%= will_paginate @chefs %>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Enter a new ingredient" %>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "#{@ingredient.name}" %>

<% if @ingredient.recipes.count != 0 %>
  <h4 align="center">Recipe's containing <%= @ingredient.name %></h4>
  <div align="center">
    <%= will_paginate @ingredient_recipe %>
  </div>
  <%= render 'recipes/recipe', obj: @ingredient_recipe %>
  <div align="center">
    <%= will_paginate @ingredient_recipe %>
  </div>
<% else %>
  <h4 align="center">No recipes yet!</h4>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer center">
  <small>
    <strong>By <em>Cesar Luque</em></strong>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
    </ul>
    <p>&copy; 2016 Company, Inc.</p>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<% if flash.count > 0 %>
  <div class="alert alert-success" role="alert">
    <% flash.each do |name, msg| %>
    <ul>
      <%= msg %>
    </ul>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipies", root_path, class: "navbar-brand", id: "logo" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Chefs', pages_path %></li>
        <li><%= link_to "All Recipes", recipes_path %></li>
        <% if chef_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add Recipe", new_recipe_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Ingredients", ingredients_path %></li>
          <% Ingredient.all.each do |ingredient| %>
            <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
          <% end %>
          <% if chef_signed_in? && current_chef.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "New Ingredient", new_ingredient_path %></li>
          <% end %>

        </ul>
      </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if chef_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.capitalize %>'s Profile <%= "Admin" if current_chef.admin? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "View your listing of recipes", page_path(current_chef) %></li>
            <li><%= link_to "Edit your profile", edit_chef_registration_path(current_chef)  %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", destroy_chef_session_path, method: :delete  %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to 'Log In', new_chef_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron center">
  <div class="container">
    <h1>Welcome to MyRecipies!</h1>
    <h2>The best recipe sharing app!.</h2>

    <p><%= link_to "All Recipes listing", recipes_path, class: "btn btn-danger btn-lg btn-xlarge"  %></p>
  </div>

</div>

<div class="row">
    <div class="col-lg-4">
      <h2>Safari bug warning!</h2>
      <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
    </div>
</div>

app/views/pages/index.html.erb
<%= render 'shared/page_title', title: "Showing all chefs" %>

<div align="center">
  <%= will_paginate @chefs %>
  <% @chefs.each do |chef| %>
    <ul class="linting">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(chef), page_path(chef) %></li>
          <li class="chef-title"><%= link_to chef.chefname.capitalize, page_path(chef) %></li>
          <li><small><%= pluralize(chef.recipes.count, "recipe") if chef.recipes %></small></li>
          <% if chef_signed_in? && current_chef.admin? && !chef.admin? %>
              <li><%= link_to "Delete this Chef", page_path(chef), method: :delete, data: { confirm: "Are you sure you want to delete this chef and all associated recipes?" } %></li>
          <% end %>

        </div>
      </div>
    </ul>
  <% end %>

  <%= will_paginate @chefs %>
</div>

app/views/pages/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.chefname}'s profile" %>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for(@chef, size: 150) %>
  </div>
</div>
<% if @chef.recipes.count != 0 %>
  <h4 align="center"><%= @chef.chefname.capitalize %>'s recipes</h4>
  <div align="center">
    <%= will_paginate @chef_recipes %>
  </div>
  <%= render 'recipes/recipe', obj: @chef_recipes %>
  <div align="center">
    <%= will_paginate @chef_recipes %>
  </div>
<% else %>
  <h4 align="center">No recipes yet!</h4>
<% end %>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= simple_form_for(@recipe) do |f| %>
      <div class="form-group">

        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>

      <div class="form-group">

        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>

      <div class="form-group">

          <div class="col-md-8 col-md-offset-2">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
              <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>

      </div>

      <div class="form-group">
        <div class="col-md-10 col-offset-2 colormatch">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>

<% end %>

    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipe listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
    <section class="chef_info center">
      <%= gravatar_for(recipe.chef, size: 120) %>
    </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%=simple_format( truncate(recipe.description, length: 150)) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %>
                                                                                        | <%= pluralize(recipe.comments.count, 'Comment') %></small></span>
      </p>

      <% if chef_signed_in? && (current_chef == recipe.chef  || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "Showing all recipes" %>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<hr>
<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description">
    <strong>Steps: </strong>
  </h4>
  <%= simple_format(@recipe.description) %>
  <% if @recipe.ingredients.any? %>
     <p>Ingredients: <%= render @recipe.ingredients %> </p>
  <% end %>
  <div class="pull-right">
    <p class="center">

        <em>Created by:</em>
    </p>

    <p class="center">
      <%= link_to gravatar_for(@recipe.chef), page_path(@recipe.chef) %>
    </p>

    <p class="center">
      <small><%= @recipe.chef.chefname %></small>
      <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-actions">

    <% if chef_signed_in? && (@recipe.chef == current_chef || current_chef.admin?)  %>
      <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
      <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
    <% end %>



    <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>
  </div>
</div>
<% if chef_signed_in? %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Comments:</h3>
    <hr>
    <%= simple_form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>


      <div class="form-group">

        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter comment here" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-10 col-offset-2 colormatch">
          <%= f.submit 'Submit Comment', class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>

<% end %>
<hr>

  </div>
</div>

<% end %>

<% if @recipe.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>

app/views/shared/_flashmessages.html.erb
<% if flash.count > 0 %>
  <div class="alert alert-success" role="alert">
    <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 class="text-center"><%= title.capitalize %></h1>